version: '3'

volumes:
  data:
services:
  grader:
    image: apluslms/run-mooc-grader
    command: "python3 manage.py runserver 0.0.0.0:8080 --noreload"
    volumes:
      - data:/data
      - /var/run/docker.sock:/var/run/docker.sock
      - /tmp/aplus:/tmp/aplus
      - ../../aplus-manual/:/srv/courses/default:ro
    ports:
      - "8080:8080"
  plus:
    image: apluslms/run-aplus-front
    command: "python3 manage.py runserver 0.0.0.0:8000 --noreload"
    environment:
      APLUS_BASE_URL: 'http://localhost:8000/'
      USE_GITMANAGER: 'false'
    volumes:
      - data:/data
      - ../:/src/aplus/:ro
    ports:
      - "8000:8000"
    depends_on:
      - grader
